Nuevo ejercicio para mostrar un "loading" durante 3 segundos cuando termina de contar
AlvaroLC/Programacion-Servicios-Procesos pull request #1
Opened 2021-10-04 16:34 UTC by AlvaroLC

2021-10-04 16:41 UTC, jmperezra commented
Hola, @AlvaroLC !

2021-10-04 16:47 UTC, jmperezra requested changes

2021-10-04 16:47 UTC, jmperezra commented on app/src/main/java/com/alvarolc/psp_playground/MainActivity.kt
> +    private fun progressBar2() {
Hola, quizás un nombre más descriptivo en la función ayudaría a averiguar qué pretende hacer la función.

2021-10-04 16:51 UTC, AlvaroLC commented on app/src/main/java/com/alvarolc/psp_playground/MainActivity.kt
> +    private fun progressBar2() {
He tenido en cuenta tu comentario y he cambiado el nombre de la función por "progressBarWhileCounting" que es bastante más descriptivo. Gracias!

2021-10-08 14:00 UTC, ghost requested changes
Hola, te he solicitado un cambio para optimizar el código.

2021-10-08 14:00 UTC, jmperezra commented on app/src/main/java/com/alvarolc/psp_playground/ut01/ThreadActivity.kt
> +                    spinner.visibility = View.VISIBLE
En este bucle estás ejecutando 10 veces una función que sólo es necesaria ejecutarla una vez: 
``` spinner.visibility = View.VISIBLE ````
Esto provoca que ejecute código innecesario y por tanto, consumo de máquina innecesaria. ¿Cómo lo solucionarías?

2021-10-13 13:35 UTC, AlvaroLC commented on app/src/main/java/com/alvarolc/psp_playground/ut01/ThreadActivity.kt
> +                    spinner.visibility = View.VISIBLE
Hola! He tenido en cuenta tu consejo, y he optimizado el código extrayendo ``` spinner.visibility = View.VISIBLE ```` del bucle for y colocándolo justo encima de éste, de esta manera solo se ejecuta una vez, al terminar el bucle for se vuelve invisible. Gracias por tu observación.

2021-10-13 13:51 UTC, ghost commented on app/src/main/java/com/alvarolc/psp_playground/ut01/ThreadActivity.kt
> +                    spinner.visibility = View.VISIBLE
Genial!

2021-10-27 09:28 UTC, ghost requested changes
Por favor, asegúrate que has subido todos los cambios porque sigue sin corregirse lo del cambio de visibilidad dentro del bucle.

2021-10-27 09:28 UTC, ghost commented on app/src/main/java/com/alvarolc/psp_playground/ut01/ThreadActivity.kt
> +                    spinner.visibility = View.VISIBLE
¿Está corregido? No lo veo en el código.

2021-10-28 16:38 UTC, ghost approved these changes
Genial!

2021-10-28 16:38 UTC, merged